name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # Push image to Docker Hub and GitHub Container Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    # needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        ycsb: [0.17.0]

    steps:
      - uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tags
        id: tags
        run: |
          # Get date in YYYYMMDDhhmmss format. April 29st 2021 09:30:00 will result in 20210429093000.
          DATE=$(date '+%Y%m%d%H%M%S')

          # [ "$GITHUB_REF" == "refs/heads/main" ] && echo "::set-output name=hub-latest::jaconi/ycsb:${{ matrix.ycsb }}-latest"
          [ "$GITHUB_REF" == "refs/heads/main" ] && echo "::set-output name=ghcr-latest::ghcr.io/${{ github.repository }}:${{ matrix.ycsb }}-latest"

          # echo "::set-output name=hub::jaconi/ycsb:${{ matrix.ycsb }}-$DATE"
          echo "::set-output name=ghcr::ghcr.io/${{ github.repository }}:${{ matrix.ycsb }}-$DATE"

      - uses: docker/build-push-action@v2
        with:
          build-args: YCSB_VERSION=${{ matrix.ycsb }}
          push: true
          tags: ${{ join(steps.tags.outputs.*, ',') }}
